### ISSUE TITLE
cpu.model.name fails to build with: `NixVirt: expected set or null, found lambda`

### ISSUE THREAD

**Issue by Libadoxon** [AshleyYakeley/NixVirt#66]
When a domain sets cpu.model.name the evaluation is aborted with: `error: evaluation aborted with the following error message: 'NixVirt: expected set or null, found lambda'`.
Minimal working example:
```nix
nixvirt.lib.domain.writeXML { 
  name = "foo";
  cpu = {
    model = {
      name = "test";
    };
  };
}
```

**Comment by AshleyYakeley** [comment]
OK, I think I see the cause.

**Comment by AshleyYakeley** [comment]
OK, fixed now.

**Comment by Libadoxon** [comment]
okay so I couldn't find any other broken attributes, no idea why I was still getting the error message. Maybe something was cached weird. Anyway everything is resolved now.
